# Generated by Django 4.1.4 on 2022-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_is_deleted_alter_blog_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogtype',
            field=models.TextField(choices=[('HOMEPAGE', 'HOMEPAGE'), ('SINGLEPAGE', 'SINGLEPAGE'), ('BLOGPAGE', 'BLOGPAGE')], default='SINGLEPAGE', max_length=20),
        ),
    ]
